global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'music-catalog-service'
    metrics_path: '/music/actuator/prometheus'
    static_configs:
      - targets: ['172.22.80.1:8081'] ## only for demo purposes don't use host.docker.internal in production